name: escola

services:
  auth-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: auth-service
    ports:
      - "${CLIENT_SERVICE_PORT}:${CLIENT_SERVICE_PORT}"
      - "${CLIENT_SERVICE_DEBUG_PORT}:${CLIENT_SERVICE_DEBUG_PORT}"
    volumes:
      - .:/app
    env_file:
      - ./.env
    networks:
      - escola-network

networks:
  escola-network:
    driver: bridge